# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7908c844e9d7cd8252128a5ec47766989dd854f6adda2db4690f2bf65723539fb3cb4a434c8515499945c506efb0b62bad6376ca00fc5965ff9cba86a6e60b0

test:
  secret_key_base: d3ac116b56155553ba43caa3f9fa38ea88b1484891c23d5c6ad45dca2730c0524f7e9c0f573cee355ba1c233f96b2249834de51370d99cf6fe1a7e3802365c6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
